---
- hosts: all
  become: true
  pre_tasks:
  - name: install updates (Kali)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Kali"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: Ubuntu_Clients
  become: true
  tasks:
  - name: install apache2 and PHP support packages
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: Create default html site
    tags: apache,apache,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
