---
- hosts: all
  become: true
  pre_tasks:
  - name: install updates (Kali)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Kali"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: Workstations
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: all
  become: true
  tasks:
    - name: create user
      tags: always
      user:
        name: ansible
        groups: root
    - name: add ssh key for user
      tags: always
      authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDP8C12RrEcPtisGUdLSLgutLou4t0O47fwlJksXKq5/ ansible"
    - name: add ansible to sudoers file
      tags: always
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

- hosts: Ubuntu_Clients
  become: true
  tasks:
  - name: install apache2 and PHP support packages
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: Create default html site
    tags: apache,apache,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  - name: change title for default website
    tags: apache,apache2
    lineinfile:
      path: /var/www/html/index.html
      regexp: '^ServerAdmin'
      line: ServerAdmin tj@tjhouston.com
    when: ansible_distribution == "Ubuntu"

  - name: start service
    tags: apache2
    service:
      name: apache2
      state: started
      enabled: yes

    when: ansible_distribution == "Ubuntu"
