---
- hosts: all
  become: true
  tasks:
  - name: install updates (Kali)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Kali"

- name: install updates (Ubuntu)
  apt:
    update_only: yes
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- hosts: Ubuntu_Clients
  become: true
  tasks:
  - name: install apache2 and PHP support packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution = "Ubuntu"
